### ISSUE TITLE
Error when trying to install any modpack

### ISSUE THREAD

**Issue by maxcmiller** [TechnicPack/TechnicLauncher#1187]
Whenever I try to click the "Install" button for a modpack, the loading bar shows for a brief moment and then nothing happens. When I open the console, I see the following stack trace each time:

``` java
[B#301] java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;[Ljava/lang/Object;Ljava/lang/Throwable;)V
[B#301]     at org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory$Slf4jLoggerEx.debug(Slf4jLoggerFactory.java:167)
[B#301]     at org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider.newLocalRepositoryManager(DefaultLocalRepositoryProvider.java:116)
[B#301]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.newLocalRepositoryManager(DefaultRepositorySystem.java:421)
[B#301]     at net.technicpack.utilslib.maven.MavenConnector.<init>(MavenConnector.java:67)
[B#301]     at net.technicpack.minecraftcore.install.tasks.HandleVersionFileTask.<init>(HandleVersionFileTask.java:55)
[B#301]     at net.technicpack.launcher.launch.Installer.buildTasksQueue(Installer.java:252)
[B#301]     at net.technicpack.launcher.launch.Installer$1.run(Installer.java:111)
[B#301]     at java.lang.Thread.run(Thread.java:745)
[B#301] Unhandled Exception in Thread[Thread-77,6,main]
```

I'm using OS X Yosemite 10.10.3 and Oracle's Java version 1.8.0_45, with both the JRE and JDK installed. Also, I have the latest Technic Launcher for OS X downloaded from the website.

I have tried deleting the technic folder and reinstalling multiple times, with no luck.

**Comment by CannibalVox** [comment]
I apologize for not responding sooner- this build is a little out of date, can you show me a log from a more recent build?

**Comment by maxcmiller** [comment]
Sure - I downloaded the latest launcher from the website (v4.308), and I'm getting a very similar error.

``` java
[B#308] java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;[Ljava/lang/Object;Ljava/lang/Throwable;)V
[B#308]     at org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory$Slf4jLoggerEx.debug(Slf4jLoggerFactory.java:167)
[B#308]     at org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider.newLocalRepositoryManager(DefaultLocalRepositoryProvider.java:116)
[B#308]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.newLocalRepositoryManager(DefaultRepositorySystem.java:421)
[B#308]     at net.technicpack.utilslib.maven.MavenConnector.<init>(MavenConnector.java:67)
[B#308]     at net.technicpack.minecraftcore.install.tasks.HandleVersionFileTask.<init>(HandleVersionFileTask.java:55)
[B#308]     at net.technicpack.launcher.launch.Installer.buildTasksQueue(Installer.java:283)
[B#308]     at net.technicpack.launcher.launch.Installer$1.run(Installer.java:115)
[B#308]     at java.lang.Thread.run(Thread.java:745)
[B#308] Unhandled Exception in Thread[Thread-36,6,main]
```

**Comment by fiatalur2004** [comment]
no aplication

**Comment by CannibalVox** [comment]
Sorry, hi, I'm having a hard time keeping up.  

Go to:  %appdata%.technic\assets\launcher on your system.  Is there an aether-dep.jar there?

**Comment by CannibalVox** [comment]
Gosh, you already told me you were on OSX, I'm so sorry.  ~/Library/Application Support/technic/assets/launcher

**Comment by maxcmiller** [comment]
No problem - yep, `aether-dep.jar` is there.

**Comment by CannibalVox** [comment]
If you delete it and restart the launcher, does it redownload, and does that fix it?

**Comment by maxcmiller** [comment]
I deleted the technic folder and started the launcher, the files did redownload, but the issue persists.

**Comment by Hucinec** [comment]
Launcher Build: 0

```
Selected Pack: Vanilla
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.8.0_45 64 bit
    Total Memory: 155 MB
    Max Memory: 1806 MB
    Memory Free: 82 MB
    CPU Cores: 4

**Comment by xsznix** [comment]
I had the same issue as well. Do you have anything inside `/Library/Java/Extensions`? Something in there may be causing the wrong version of `slf4j` to be loaded. I just moved everything inside that folder somewhere else, and installing modpacks worked.

**Comment by maxcmiller** [comment]
@xsznix There were several `.jar` files in `/Library/Java/Extensions`, I deleted them all. This didn't fix the issue unfortunately.

**Comment by xsznix** [comment]
Try `~/Library/Java/Extensions`?

**Comment by icninja** [comment]
Hi, im still having this issue today; im unable to download any packs. Im using a mac with the latest version of Java, and still having issues. Upon investigating the logs, i discovered that the application is only receiving 256mb of ram, where it should be getting at least 512. Whats the best way to fix this?

**Comment by WIREDEED** [comment]
im having the same issue
here is the promt 
[B#554] java.lang.NoClassDefFoundError: org/eclipse/aether/impl/DefaultServiceLocator$ErrorHandler
[B#554] 	at net.technicpack.minecraftcore.install.tasks.HandleVersionFileTask.<init>(HandleVersionFileTask.java:60)
[B#554] 	at net.technicpack.launcher.launch.Installer.buildTasksQueue(Installer.java:282)
[B#554] 	at net.technicpack.launcher.launch.Installer$1.run(Installer.java:114)
[B#554] 	at java.lang.Thread.run(Unknown Source)
[B#554] Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.impl.DefaultServiceLocator$ErrorHandler
[B#554] 	at java.net.URLClassLoader.findClass(Unknown Source)
[B#554] 	at com.regexlab.j2e.Jar2ExeClassLoader.findClass(Unknown Source)
[B#554] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[B#554] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[B#554] 	... 4 more
[B#554] Unhandled Exception in Thread[Thread-67,6,main]
there is no aether-dep.jar in the %appdata%.technic\assets\launcher

**Comment by WIREDEED** [comment]
please help

**Comment by Pyker** [comment]
@WIREDEED 1) Don't hijack an old issue that's irrelevant to your case; 2) Don't use a cracked launcher.
