### ISSUE TITLE
NoSuchMethod Error: org.apache.commons.codec.digest.DigestUtils.md5Hex 

### ISSUE THREAD

**Issue by dunklesToast** [TechnicPack/TechnicLauncher#1261]
Hey,

I just wanted to "install" technic launcher but it stucks at Downloading the OpenSans Font. It gives following error:

`java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.md5Hex(Ljava/io/InputStream;)Ljava/lang/String;
	at net.technicpack.utilslib.MD5Utils.getMD5(MD5Utils.java:34)
	at net.technicpack.launchercore.install.verifiers.MD5FileVerifier.isFileValid(MD5FileVerifier.java:38)
	at net.technicpack.autoupdate.tasks.QueryUpdateStream.runTask(QueryUpdateStream.java:79)
	at net.technicpack.launchercore.install.InstallTasksQueue.runAllTasks(InstallTasksQueue.java:52)
	at net.technicpack.autoupdate.Relauncher.runAutoUpdater(Relauncher.java:103)
	at net.technicpack.launcher.LauncherMain.main(LauncherMain.java:193)`

When I force quit it and restart it the same error occurs.

FYI: It downloaded the Font correctly and the font is working!

System:
macOS Sierra 10.12.4
java 1.8_121

**Comment by juniarz** [comment]
I resolved this issue by removing any conflicting libraries at:
`/Users/<username>/Library/Java/Extensions/`
