### ISSUE TITLE
You're not alone pack causes Minecraft to crash on startup

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#277]
Launching the "You're not alone pack" from the Technic Launcher is causing Minecraft to crash during startup. See the Minecraft log below.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/24/13 5:39 PM
Description: Failed to start game

java.lang.RuntimeException: Unknown character ' ' in 'C:/Users/house/AppData/Roaming/.technic/youre-not-alone-pack/config/forestry/base.conf:1'
    at net.minecraftforge.common.Configuration.load(Configuration.java:625)
    at net.minecraftforge.common.Configuration.<init>(Configuration.java:100)
    at forestry.core.config.Config.load(Config.java:100)
    at forestry.core.ForestryCore.preInit(ForestryCore.java:55)
    at forestry.Forestry.preInit(Forestry.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:514)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:160)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:410)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:732)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.1
    Operating System: Windows Vista (x86) version 6.0
    Java Version: 1.6.0_33, Sun Microsystems Inc.
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Sun Microsystems Inc.
    Memory: 112746528 bytes (107 MB) / 235073536 bytes (224 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 1 total; -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.44 FML v5.1.43.682 Minecraft Forge 7.7.2.682 40 mods loaded, 40 mods active
    mcp{7.44} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{5.1.43.682} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
    Forge{7.7.2.682} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{0.8.6.3} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.5.2.10} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized
    PowerCrystalsCore{1.1.3} [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized
    mod_bspkrsCore{v2.02(1.5.1)} [bspkrsCore]([1.5.1]bspkrsCorev2.02.zip) Unloaded->Constructed->Pre-initialized
    GuiAPI{0.15.4} [GuiAPI](modpack.jar) Unloaded->Constructed->Pre-initialized
    TreeCapitator{Forge 1.5.1.r01} [TreeCapitator]([1.5.1]TreeCapitator.Forge.1.5.1.r01.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{2.6.4} [Damage Indicators]([1.5.1]DamageIndicators v2.6.4.zip) Unloaded->Constructed->Pre-initialized
    mod_ReiMinimap{v3.3_04 [1.5.1]} [mod_ReiMinimap]([1.5.1]ReiMinimap_v3.3_04.zip) Unloaded->Constructed->Pre-initialized
    Backpack{1.7.8} [Backpack](backpack-1.7.8-1.5.1.zip) Unloaded->Constructed->Pre-initialized
    BattleTowers{1.3.2} [Battle Towers](BattleTowers_1.5.1.zip) Unloaded->Constructed->Pre-initialized
    BetterDungeons{1.0.1} [Better dungeons](BetterDungeons.zip) Unloaded->Constructed->Pre-initialized
    BiomesOPlenty{0.5.1} [Biomes O' Plenty](Biomes-O-Plenty-0.5.1.zip) Unloaded->Constructed->Pre-initialized
    ClaySoldiersMod{9.1} [Clay Soldiers Mod](CSM_v911.jar) Unloaded->Constructed->Pre-initialized
    CustomSpawner{1.12.5} [DrZhark's CustomSpawner](CustomMobSpawner 1.12.5.zip) Unloaded->Constructed->Pre-initialized
    DimensionalDoors{1.5.2R1.3.6RC1} [Dimensional Doors](DimensionalDoors-1.5.1 1.3.5.1.zip) Unloaded->Constructed->Pre-initialized
    MoCreatures{5.1.5} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v5.1.5.zip) Unloaded->Constructed->Pre-initialized
    eplus{1.14.6} [Enchanting Plus](EnchantingPlus-1.14.6.jar) Unloaded->Constructed->Pre-initialized
    FlansMod{2.3} [Flan's Mod](Flans Mod 2.3 for Minecraft 1.5.1 Universal.zip) Unloaded->Constructed->Pre-initialized
    Flashlight{0.1.1} [Flashlight](flashlight.zip) Unloaded->Constructed->Pre-initialized
    Forestry{2.2.0.2} [Forestry for Minecraft](forestry-A-2.2.0.2.jar) Unloaded->Constructed->Errored
    iChunUtil{1.0.1} [iChunUtil](iChunUtil1.0.1.zip) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.53} [Inventory Tweaks](InventoryTweaks-1.53.jar) Unloaded->Constructed->Pre-initialized
    IronChest{5.2.4.389} [Iron Chest](ironchest-universal-1.5.1-5.2.4.389.zip) Unloaded->Constructed->Pre-initialized
    MCA{3.3.1} [Minecraft Comes Alive](mca v3.3.1.zip) Unloaded->Constructed->Pre-initialized
    Millenaire{4.9.0} [Millénaire](millenaire4.9.0.zip) Unloaded->Constructed->Pre-initialized
    MutantCreatures{1.3.3} [Mutant Creatures](Mutant Creatures v1.3.3 mc1.5.1.zip) Unloaded->Constructed->Pre-initialized
    NetherOres{1.5.1R2.1.3} [Nether Ores](NetherOres-2.1.3-60.jar) Unloaded->Constructed->Pre-initialized
    PortalGun{1.5.1} [PortalGun](PortalGun1.5.1.zip) Unloaded->Constructed->Pre-initialized
    AS_Ruins{9.9} [Ruins Spawning System](Ruins_1.5.1.zip) Unloaded->Constructed->Pre-initialized
    SAP_Man{1.4.2} [SanAndreasPs Managers](SAP_ManPack_v142.jar) Unloaded->Constructed->Pre-initialized
    TStormFix{1.0} [Thunderstorm Fix](SAP_ManPack_v142.jar) Unloaded->Constructed->Pre-initialized
    mod_TaleOfKingdoms{Not available} [mod_TaleOfKingdoms](Tale-of-Kingdoms-V1.4.2.9.zip) Unloaded->Constructed->Pre-initialized
    TaleOfKingdoms{1.4.2.9} [Tale of Kingdoms](Tale-of-Kingdoms-V1.4.2.9.zip) Unloaded->Constructed->Pre-initialized
    Thaumcraft{3.0.4c} [Thaumcraft](Thaumcraft3.0.4c.zip) Unloaded->Constructed->Pre-initialized
    TwilightForest{1.17.2} [The Twilight Forest](twilightforest-1.17.2.zip) Unloaded->Constructed->Pre-initialized
    AS_UpdateCheck{1.0.7} [AtomicStryker Update Check Mod](UpdateCheckerMod_1.5.1.zip) Unloaded->Constructed->Pre-initialized
    weaponmod{1.5.1 v1.11.2} [Balkon's WeaponMod](WeaponMod.zip) Unloaded->Constructed->Pre-initialized
    LWJGL: 2.4.2
    OpenGL: Quadro NVS 140M/PCI/SSE2 GL version 2.1.2, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by Salynne** [comment]
This is an issue with the You're not alone pack, not the launcher. Please report the issue to the modpack creator.

**Comment by ghost** [comment]
And how would one go about doing that? The only place I can find information about the modpack is on the TechnicLauncher site.
