### ISSUE TITLE
Voltz keeps crashing :(

### ISSUE THREAD

**Issue by kster** [TechnicPack/TechnicLauncher#296]
whenever i try play the voltz mod pack on the technic launcher it always crashes.
Crash Report:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 10/10/13 11:37 AM
Description: Failed to start game

cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:147)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:697)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:213)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:448)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:733)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
    at mods.neiplugins.common.Utils.getBooleanSetting(Utils.java:218)
    at mods.neiplugins.options.VersionCheck.checkForNewVersion(VersionCheck.java:34)
    at mods.neiplugins.NEIPlugins_Stat.init(NEIPlugins_Stat.java:39)
    at mods.neiplugins.NEIPlugins.initPlugins(NEIPlugins.java:202)
    at mods.neiplugins.NEIPlugins.postInit(NEIPlugins.java:261)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696)
    ... 5 more
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\
***_\AppData\Roaming.technic\voltz\config\NEI.cfg (The requested operation cannot be performed on a file with a user-mapped section open)
    at codechicken.core.config.ConfigFile.saveConfig(ConfigFile.java:134)
    at codechicken.core.config.ConfigTagParent.setNewLineMode(ConfigTagParent.java:94)
    at codechicken.nei.NEIClientConfig.setDefaults(NEIClientConfig.java:83)
    at codechicken.nei.NEIClientConfig.<clinit>(NEIClientConfig.java:73)
    ... 36 more
Caused by: java.io.FileNotFoundException: C:\Users\**_*\AppData\Roaming.technic\voltz\config\NEI.cfg (The requested operation cannot be performed on a file with a user-mapped section open)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.PrintWriter.<init>(Unknown Source)
    at codechicken.core.config.ConfigFile.saveConfig(ConfigFile.java:130)
    ... 39 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 97070096 bytes (92 MB) / 219574272 bytes (209 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 1 total; -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.51 FML v5.2.23.737 Minecraft Forge 7.8.1.737 49 mods loaded, 49 mods active
    mcp{7.51} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    FML{5.2.23.737} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Forge{7.8.1.737} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    CodeChickenCore{0.8.7.3} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    CoFHFramework{1.5.2.5} [CoFH Framework](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ImmibisMicroblocks{55.0.7} [Immibis's Microblocks](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NotEnoughItems{1.5.2.28} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    PowerCrystalsCore{1.1.6} [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    CoFHCore{1.5.2.5} [CoFHCore](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    CoFHWorld{1.5.2.5} [CoFHWorld](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    GalacticraftCore{0.1.36} [Galacticraft Core](Galacticraft-1.5.2-a0.1.36.410.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ImmibisMicroblocksInstallCheck{55.0.7} [Immibis's Microblocks (Checks for incorrect installation, ignore this)](immibis-microblocks-55.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_ReiMinimap{v3.3_06 [1.5.2]} [mod_ReiMinimap]([1.5.2]ReiMinimap_v3.3_06.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded{1.5.1R2.6.4} [MineFactory Reloaded](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    AppliedEnergistics{rv11.c} [Applied Energistics](appeng-rv11-c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    AtomicScience{0.6.2} [Atomic Science](Atomic_Science_v0.6.2.117.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ExtrabiomesXL{3.13.4} [ExtrabiomesXL](ExtrabiomesXL-universal-1.5.2-3.13.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ICBM|Contraption{1.2.1} [ICBM](ICBM_Contraption_v1.2.1.172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ICBM|Sentry{1.2.1} [ICBM](ICBM_Sentry_v1.2.1.172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ICBM|Explosion{1.2.1} [ICBM](ICBM_Explosion_v1.2.1.172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ImmibisCore{55.1.6} [Immibis Core](immibis-core-55.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    inventorytweaks{1.54b} [Inventory Tweaks](InventoryTweaks-1.54b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Mekanism{5.5.6} [Mekanism](Mekanism-v5.5.6.bugfix1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MekanismGenerators{5.5.6} [MekanismGenerators](MekanismGenerators-v5.5.6.bugfix1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MekanismTools{5.5.6} [MekanismTools](MekanismTools-v5.5.6.bugfix1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MFFS{3.1.0} [Modular Force Field System](MFFS_v3.1.0.175.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.5.1R2.6.4} [MFR Compat: Applied Energistics](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatAtum{1.5.1R2.6.4} [MFR Compat: Atum](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatBackTools{1.5.1R2.6.4} [MFR Compat: BackTools](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatBiomesOPlenty{1.5.1R2.6.4} [MFR Compat: Biomes O' Plenty](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatChococraft{1.5.1R2.6.4} [MFR Compat: Chococraft](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.5.1R2.6.4} [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatForestry{1.5.1R2.6.4} [MFR Compat: Forestry](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatForestryPre{1.5.1R2.6.4} [MFR Compat: Forestry (2)](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatIC2{1.5.1R2.6.4} [MFR Compat: IC2](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatMagicalCrops{1.5.1R2.6.4} [MFR Compat: Magical Crops](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatMystcraft{1.5.1R2.6.4} [MFR Compat: Mystcraft](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatPams{1.5.1R2.6.4} [MFR Compat: Pam's Mods](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatRP2{1.5.1R2.6.4} [MFR Compat: RP2](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatSoulShards{1.5.1R2.6.4} [MFR Compat: SoulShards](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.5.1R2.6.4} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MFReloaded|CompatThaumcraft{1.5.1R2.6.4} [MFR Compat: Thaumcraft](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.5.1R2.6.4} [MFR Compat: Thermal Expansion](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatTwilightForest{1.5.1R2.6.4} [MFR Compat: TwilightForest](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatVanilla{1.5.1R2.6.4} [MFR Compat: Vanilla](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatXyCraft{1.5.1R2.6.4} [MFR Compat: XyCraft](MineFactoryReloaded-2.6.4-975.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mmmPowersuits{0.7.0-534} [MachineMuse's Modular Powersuits](ModularPowersuits-0.7.0-534.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    PowersuitAddons{0.2.3-144} [Andrew2448's Modular Powersuits Addon](MPSA-0.2.3-144_MPS-531+.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NEIPlugins{1.0.9.3} [NEI Plugins](NEIPlugins-1.0.9.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
    LWJGL: 2.4.2
    OpenGL: Intel(R) HD Graphics GL version 3.3.0 - Build 8.15.10.2712, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by kster** [comment]
please help. :D
