### ISSUE TITLE
Fix solder packs not syncing occassionally

### ISSUE THREAD

**Issue by Spyboticsguy** [TechnicPack/TechnicLauncher#303]
At some points, the solder packs will become appended with the word 'null' - this breaks resource downloading and pack synchronization.

**Comment by ghost** [comment]
I'm also having this issue. Here's the console output.

```
InstalledPack{info=SolderPackInfo{name='daysofyore', display_name='Days of Yore', url='null', icon_md5='d41d8cd98f00b204e9800998ecf8427e', logo_md5='d41d8cd98f00b204e9800998ecf8427e', background_md5='d41d8cd98f00b204e9800998ecf8427e', recommended='0.9.6.3', latest='0.9.6.3', builds=[0.9.6.2, 0.9.6.3], solder=net.technicpack.launchercore.restful.solder.Solder@147ed19}, name='daysofyore', platform=true, build='latest', directory='launcher\daysofyore'}
Pack: daysofyore Image Download Worker Calculated MD5: 6ee5304d806607d7c30272bd2e6c734b Required MD5: d41d8cd98f00b204e9800998ecf8427e
Starting download of nulldaysofyore/resources/background.jpg, with 3 tries remaining
Failed to download and load image from: nulldaysofyore/resources/background.jpg
java.net.MalformedURLException: no protocol: nulldaysofyore/resources/background.jpg
    at java.net.URL.<init>(URL.java:585)
    at java.net.URL.<init>(URL.java:482)
    at java.net.URL.<init>(URL.java:431)
    at net.technicpack.launchercore.util.Download.<init>(Download.java:48)
    at net.technicpack.launchercore.util.DownloadUtils.downloadFile(DownloadUtils.java:73)
    at net.technicpack.launchercore.util.DownloadUtils.downloadFile(DownloadUtils.java:109)
    at net.technicpack.launchercore.util.DownloadUtils.downloadFile(DownloadUtils.java:113)
    at net.technicpack.launchercore.install.InstalledPack$1.run(InstalledPack.java:275)
Pack: daysofyore Image Download Worker Calculated MD5: 14dfeeda8c5273185e465eec12e84cbc Required MD5: d41d8cd98f00b204e9800998ecf8427e
Starting download of nulldaysofyore/resources/icon.png, with 3 tries remaining
Failed to download and load image from: nulldaysofyore/resources/icon.png
java.net.MalformedURLException: no protocol: nulldaysofyore/resources/icon.png
    at java.net.URL.<init>(URL.java:585)
    at java.net.URL.<init>(URL.java:482)
    at java.net.URL.<init>(URL.java:431)
    at net.technicpack.launchercore.util.Download.<init>(Download.java:48)
    at net.technicpack.launchercore.util.DownloadUtils.downloadFile(DownloadUtils.java:73)
    at net.technicpack.launchercore.util.DownloadUtils.downloadFile(DownloadUtils.java:109)
    at net.technicpack.launchercore.util.DownloadUtils.downloadFile(DownloadUtils.java:113)
    at net.technicpack.launchercore.install.InstalledPack$1.run(InstalledPack.java:275)
```

**Comment by GenPage** [comment]
+1

**Comment by CannibalVox** [comment]
We have confirmed that this issue is fixed in the launcher's beta stream.

**Comment by Spyboticsguy** [comment]
Cool - thanks.
