### ISSUE TITLE
Launcher doesn't build

### ISSUE THREAD

**Issue by admiral0** [TechnicPack/TechnicLauncher#36]
OS: Gentoo GNU/Linux
JDK: java version "1.6.0_31",Java(TM) SE Runtime Environment (build 1.6.0_31-b04), Java HotSpot(TM) 64-Bit Server VM (build 20.6-b01, mixed mode)
Maven:Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)

Are you using 1.7 features?

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Technic Launcher 0.5.4.9
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for junit:junit:jar:4.10 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for commons-codec:commons-codec:jar:1.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.yaml:snakeyaml:jar:1.9 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ technic-launcher ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource to .
[INFO] Copying 7 resources to org/spoutcraft/launcher
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ technic-launcher ---
[INFO] Compiling 85 source files to /home/admiral0/jprojects/Spoutcraft-Launcher/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/Util.java:[45,53] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/Util.java:[53,53] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/Util.java:[61,48] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/gui/LoginForm.java:[129,24] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/gui/LoginForm.java:[179,29] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/gui/widget/CheckBoxNodeTreeSample.java:[146,7] type javax.swing.JList does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/gui/widget/CheckBoxNodeTreeSample.java:[146,31] type javax.swing.JList does not take parameters
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.781s
[INFO] Finished at: Tue Apr 03 16:37:03 CEST 2012
[INFO] Final Memory: 10M/101M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project technic-launcher: Compilation failure: Compilation failure:
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/Util.java:[45,53] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/Util.java:[53,53] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/Util.java:[61,48] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/gui/LoginForm.java:[129,24] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/gui/LoginForm.java:[179,29] type javax.swing.JComboBox does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/gui/widget/CheckBoxNodeTreeSample.java:[146,7] type javax.swing.JList does not take parameters
[ERROR] /home/admiral0/jprojects/Spoutcraft-Launcher/src/main/java/org/spoutcraft/launcher/gui/widget/CheckBoxNodeTreeSample.java:[146,31] type javax.swing.JList does not take parameters
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project technic-launcher: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:656)
        at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by admiral0** [comment]
1.6 is not compatible. Please specify it in the readme
