### ISSUE TITLE
Failed to download Ultra-Modded Survival

### ISSUE THREAD

**Issue by Jrb95** [TechnicPack/TechnicLauncher#581]
Hello, I've had this problem, where I press the download-button for Ultra-Modded Survival and it just says "Failed to download https://copy.com/80bq8qjAFKOn/modpack.zip?download=1 - Please consult the modpack author"

Now, he says that it's not on his end, so would you please tell me, what's wrong? Here's the log for the launcher:

[B#439] 2014/04/11 17:47:50 [INFO] ------------------------------------------
[B#439] 2014/04/11 17:47:50 [INFO] Technic Launcher is starting....
[B#439] 2014/04/11 17:47:50 [INFO] Launcher Build: 439
[B#439] 2014/04/11 17:47:50 [INFO] ------------ Startup Parameters ------------
[B#439] 2014/04/11 17:47:50 [INFO] --------- End of Startup Parameters ---------
[B#439] 2014/04/11 17:47:50 [INFO] Analytics Response [runLauncher]: 200
[B#439] 2014/04/11 17:47:55 [INFO] {"accessToken":"33c34b9d1b484eacbe0b2ed8bab15637","clientToken":"11e3a352-2271-402e-8aea-6869846d5761","selectedProfile":{"id":"c26daccd63b54b0c95b80f51f7dac047","name":"ShadowsStrider"}}
[B#439] 2014/04/11 17:47:55 [INFO] Launcher took: 5285ms to start
[B#439] 2014/04/11 17:47:55 [INFO] Pack: ultra-modded-survival-pack Image Download Worker Calculated MD5: 4febcbda57bab9b1ecc71f32a4a01af6 Required MD5: 93dff393db345d31ee375e2da948f067
[B#439] 2014/04/11 17:47:55 [INFO] Starting download of http://cdn.technicpack.net/platform/pack-logos/266012.png?1396740087, with 3 tries remaining
[B#439] 2014/04/11 17:47:55 [INFO] Pack: ultra-modded-survival-pack Image Download Worker Calculated MD5: 4febcbda57bab9b1ecc71f32a4a01af6 Required MD5: 93dff393db345d31ee375e2da948f067
[B#439] 2014/04/11 17:47:55 [INFO] Starting download of http://cdn.technicpack.net/platform/pack-logos/266012.png?1396740087, with 3 tries remaining
[B#439] 2014/04/11 17:48:01 [INFO] Analytics Response [installModpack]: 200
[B#439] 2014/04/11 17:48:01 [INFO] Starting download of https://copy.com/wfyoQN8eIEpk/modpack.zip?download=1, with 3 tries remaining
[B#439] 2014/04/11 17:48:02 [SEVERE] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: basic constraints check failed: pathLenConstraint violated - this cert must be the last cert in the certification path
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.process_record(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at java.net.HttpURLConnection.getResponseCode(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.mirror.download.Download.run(Download.java:70)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.mirror.MirrorStore.downloadFile(MirrorStore.java:116)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.install.tasks.DownloadFileTask.runTask(DownloadFileTask.java:37)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:32)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:108)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at org.spoutcraft.launcher.InstallThread.run(InstallThread.java:63)
[B#439] 2014/04/11 17:48:02 [SEVERE] Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: basic constraints check failed: pathLenConstraint violated - this cert must be the last cert in the certification path
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.Validator.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    ... 19 more
[B#439] 2014/04/11 17:48:02 [SEVERE] Caused by: java.security.cert.CertPathValidatorException: basic constraints check failed: pathLenConstraint violated - this cert must be the last cert in the certification path
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.provider.certpath.PKIXCertPathValidator.doValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at java.security.cert.CertPathValidator.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    ... 26 more
[B#439] 2014/04/11 17:48:02 [SEVERE] Download of https://copy.com/wfyoQN8eIEpk/modpack.zip?download=1 Failed!
[B#439] 2014/04/11 17:48:02 [INFO] Starting download of https://copy.com/wfyoQN8eIEpk/modpack.zip?download=1, with 2 tries remaining
[B#439] 2014/04/11 17:48:02 [SEVERE] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: basic constraints check failed: pathLenConstraint violated - this cert must be the last cert in the certification path
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.process_record(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at java.net.HttpURLConnection.getResponseCode(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.mirror.download.Download.run(Download.java:70)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.mirror.MirrorStore.downloadFile(MirrorStore.java:116)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.install.tasks.DownloadFileTask.runTask(DownloadFileTask.java:37)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:32)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:108)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at org.spoutcraft.launcher.InstallThread.run(InstallThread.java:63)
[B#439] 2014/04/11 17:48:02 [SEVERE] Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: basic constraints check failed: pathLenConstraint violated - this cert must be the last cert in the certification path
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.Validator.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    ... 19 more
[B#439] 2014/04/11 17:48:02 [SEVERE] Caused by: java.security.cert.CertPathValidatorException: basic constraints check failed: pathLenConstraint violated - this cert must be the last cert in the certification path
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.provider.certpath.PKIXCertPathValidator.doValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at java.security.cert.CertPathValidator.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    ... 26 more
[B#439] 2014/04/11 17:48:02 [SEVERE] Download of https://copy.com/wfyoQN8eIEpk/modpack.zip?download=1 Failed!
[B#439] 2014/04/11 17:48:02 [INFO] Starting download of https://copy.com/wfyoQN8eIEpk/modpack.zip?download=1, with 1 tries remaining
[B#439] 2014/04/11 17:48:02 [SEVERE] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: basic constraints check failed: pathLenConstraint violated - this cert must be the last cert in the certification path
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.Handshaker.process_record(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at java.net.HttpURLConnection.getResponseCode(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.mirror.download.Download.run(Download.java:70)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.mirror.MirrorStore.downloadFile(MirrorStore.java:116)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.install.tasks.DownloadFileTask.runTask(DownloadFileTask.java:37)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:32)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:108)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at org.spoutcraft.launcher.InstallThread.run(InstallThread.java:63)
[B#439] 2014/04/11 17:48:02 [SEVERE] Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: basic constraints check failed: pathLenConstraint violated - this cert must be the last cert in the certification path
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.validator.Validator.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    ... 19 more
[B#439] 2014/04/11 17:48:02 [SEVERE] Caused by: java.security.cert.CertPathValidatorException: basic constraints check failed: pathLenConstraint violated - this cert must be the last cert in the certification path
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.provider.certpath.PKIXCertPathValidator.doValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    at java.security.cert.CertPathValidator.validate(Unknown Source)
[B#439] 2014/04/11 17:48:02 [SEVERE]    ... 26 more
[B#439] 2014/04/11 17:48:02 [SEVERE] Download of https://copy.com/wfyoQN8eIEpk/modpack.zip?down

**Comment by Jrb95** [comment]
I apologize if this is a dupe - couldn't locate any thread like this. Thanks in advance.

**Comment by sniper64824** [comment]
I am also having this problem... even 2 years later than yours!
