### ISSUE TITLE
everything says loading but when i scroll down everything says add new modpach offline

### ISSUE THREAD

**Issue by bbllyy** [TechnicPack/TechnicLauncher#593]
[B#439] 2014/04/19 17:18:48 [INFO] ------------------------------------------
[B#439] 2014/04/19 17:18:48 [INFO] Technic Launcher is starting....
[B#439] 2014/04/19 17:18:48 [INFO] Launcher Build: 439
[B#439] 2014/04/19 17:18:48 [INFO] ------------ Startup Parameters ------------
[B#439] 2014/04/19 17:18:48 [INFO] --------- End of Startup Parameters ---------
[B#439] 2014/04/19 17:18:48 [WARNING] Unable to load users from C:\Users\BenYoung\AppData\Roaming.technic\users.json because it does not exist.
[B#439] 2014/04/19 17:18:48 [WARNING] Unable to load installedPacks from C:\Users\BenYoung\AppData\Roaming.technic\installedPacks because it does not exist.
[B#439] 2014/04/19 17:18:49 [WARNING] Unable to load news, hiding news section
net.technicpack.launchercore.exception.RestfulAPIException: Error accessing URL [http://www.technicpack.net/api/news/]
    at net.technicpack.launchercore.restful.RestObject.getRestObject(RestObject.java:109)
    at org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:45)
    at org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)
Caused by: java.net.SocketException: Address family not supported by protocol family: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.<init>(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at net.technicpack.launchercore.restful.RestObject.getRestObject(RestObject.java:89)
    ... 2 more
[B#439] 2014/04/19 17:18:49 [INFO] Launcher took: 1414ms to start
[B#439] 2014/04/19 17:19:12 [INFO] Auth: {"accessToken":"93a285aab3db4fceaaa785070bdc30b6","clientToken":"3b4c55da-e735-4580-9614-093f9294506c","selectedProfile":{"id":"dcfcf0f9d9664a5cab5e4868147e8b75","name":"foreveryYoung"},"availableProfiles":[{"id":"dcfcf0f9d9664a5cab5e4868147e8b75","name":"foreveryYoung"}]}
[B#439] 2014/04/19 17:19:12 [WARNING] Unable to load technic modpacks
net.technicpack.launchercore.exception.RestfulAPIException: Error accessing URL [http://solder.technicpack.net/api/modpack/?include=full&cid=8aa67b40-66ad-4c54-a84c-a3376fe574eb&u=foreveryYoung]
    at net.technicpack.launchercore.restful.RestObject.getRestObject(RestObject.java:109)
    at net.technicpack.launchercore.install.AvailablePackList$3.run(AvailablePackList.java:169)
Caused by: java.net.SocketException: Address family not supported by protocol family: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.<init>(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at net.technicpack.launchercore.restful.RestObject.getRestObject(RestObject.java:89)
    ... 1 more
[B#439] 2014/04/19 17:19:12 [INFO] Starting download of https://minotar.net/helm/foreveryYoung/100, with 3 tries remaining
[B#439] 2014/04/19 17:19:43 [INFO] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] 2014/04/19 17:20:02 [INFO] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] 2014/04/19 17:20:03 [INFO] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] 2014/04/19 17:20:03 [INFO] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] 2014/04/19 17:20:03 [INFO] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] 2014/04/19 17:20:03 [INFO] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}

**Comment by max10mason9** [comment]
i am having that same problem
