### ISSUE TITLE
All of my packs are Offline

### ISSUE THREAD

**Issue by ToasterShark** [TechnicPack/TechnicLauncher#673]
```
 Whenever I open the launcher, none of the packs (including defaults) show up.  Then if I scroll or click on one of them, they all turn to an empty ("Add New Pack") offline pack.  I tried deleting the .technic file, then re-installing, but the same issue occured.  I re-installed Java, deleted the launcher, re-installed that.  Then......... I opened it up, and clicked on the delete pack button, and this popped up:
 ( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
Launcher Build: 439
Selected Pack: null
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        java.io.File.<init>(Unknown Source)
        net.technicpack.launchercore.install.InstalledPack.getInstalledDirectory(InstalledPack.java:186)
        org.spoutcraft.launcher.skin.LauncherFrame.action(LauncherFrame.java:411)
        org.spoutcraft.launcher.skin.LauncherFrame.actionPerformed(LauncherFrame.java:399)
        javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        java.awt.Component.processMouseEvent(Unknown Source)
        javax.swing.JComponent.processMouseEvent(Unknown Source)
        java.awt.Component.processEvent(Unknown Source)
        java.awt.Container.processEvent(Unknown Source)
        java.awt.Component.dispatchEventImpl(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Window.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.7.0_60 64 bit
    Total Memory: 123 MB
    Max Memory: 1820 MB
    Memory Free: 74 MB
    CPU Cores: 8

If anyone knows what this mean, or how to fix it, please tell me.  I used to play technic on my old windows XP computer, and it worked fine, had tons of REALLY intensive packs, a crappy version of Java, and basically the worst of the worst, then I get a new computer, with windows 8.1, and _Poof_, I said goodbye to technic.

**Comment by ToasterShark** [comment]
This is what the console has to say about the issue

[B#439] {"accessToken":"4371195c992243d59b3a4facc8732c16","clientToken":"202569c8-d8bf-4282-9824-5e15d23920f2","selectedProfile":{"id":"90b3dac45b6d44d39ad6270d27494ea2","name":"Dunk320"}}
[B#439] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] InstalledPack{info=null, name='null', platform=false, build='recommended', directory='null'}
[B#439] java.util.concurrent.ExecutionException: net.technicpack.launchercore.exception.RestfulAPIException: Error accessing URL [http://www.technicpack.net/api/modpack/the-diamond-dimensions]
[B#439]     at java.util.concurrent.FutureTask.report(Unknown Source)
[B#439]     at java.util.concurrent.FutureTask.get(Unknown Source)
[B#439]     at javax.swing.SwingWorker.get(Unknown Source)
[B#439]     at org.spoutcraft.launcher.skin.options.ImportOptions$2.done(ImportOptions.java:291)
[B#439]     at javax.swing.SwingWorker$5.run(Unknown Source)
[B#439]     at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
[B#439]     at sun.swing.AccumulativeRunnable.run(Unknown Source)
[B#439]     at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
[B#439]     at javax.swing.Timer.fireActionPerformed(Unknown Source)
[B#439]     at javax.swing.Timer$DoPostEvent.run(Unknown Source)
[B#439]     at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[B#439]     at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[B#439]     at java.awt.EventQueue.access$200(Unknown Source)
[B#439]     at java.awt.EventQueue$3.run(Unknown Source)
[B#439]     at java.awt.EventQueue$3.run(Unknown Source)
[B#439]     at java.security.AccessController.doPrivileged(Native Method)
[B#439]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[B#439]     at java.awt.EventQueue.dispatchEvent(Unknown Source)
[B#439]     at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[B#439]     at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[B#439]     at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[B#439]     at java.awt.WaitDispatchSupport$2.run(Unknown Source)
[B#439]     at java.awt.WaitDispatchSupport$4.run(Unknown Source)
[B#439]     at java.security.AccessController.doPrivileged(Native Method)
[B#439]     at java.awt.WaitDispatchSupport.enter(Unknown Source)
[B#439]     at java.awt.Dialog.show(Unknown Source)
[B#439]     at java.awt.Component.show(Unknown Source)
[B#439]     at java.awt.Component.setVisible(Unknown Source)
[B#439]     at java.awt.Window.setVisible(Unknown Source)
[B#439]     at java.awt.Dialog.setVisible(Unknown Source)
[B#439]     at org.spoutcraft.launcher.skin.ModpackSelector.action(ModpackSelector.java:239)
[B#439]     at org.spoutcraft.launcher.skin.ModpackSelector.actionPerformed(ModpackSelector.java:227)
[B#439]     at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[B#439]     at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[B#439]     at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[B#439]     at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[B#439]     at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
[B#439]     at java.awt.Component.processMouseEvent(Unknown Source)
[B#439]     at javax.swing.JComponent.processMouseEvent(Unknown Source)
[B#439]     at java.awt.Component.processEvent(Unknown Source)
[B#439]     at java.awt.Container.processEvent(Unknown Source)
[B#439]     at java.awt.Component.dispatchEventImpl(Unknown Source)
[B#439]     at java.awt.Container.dispatchEventImpl(Unknown Source)
[B#439]     at java.awt.Component.dispatchEvent(Unknown Source)
[B#439]     at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[B#439]     at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[B#439]     at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[B#439]     at java.awt.Container.dispatchEventImpl(Unknown Source)
[B#439]     at java.awt.Window.dispatchEventImpl(Unknown Source)
[B#439]     at java.awt.Component.dispatchEvent(Unknown Source)
[B#439]     at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[B#439]     at java.awt.EventQueue.access$200(Unknown Source)
[B#439]     at java.awt.EventQueue$3.run(Unknown Source)
[B#439]     at java.awt.EventQueue$3.run(Unknown Source)
[B#439]     at java.security.AccessController.doPrivileged(Native Method)
[B#439]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[B#439]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[B#439]     at java.awt.EventQueue$4.run(Unknown Source)
[B#439]     at java.awt.EventQueue$4.run(Unknown Source)
[B#439]     at java.security.AccessController.doPrivileged(Native Method)
[B#439]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[B#439]     at java.awt.EventQueue.dispatchEvent(Unknown Source)
[B#439]     at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[B#439]     at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[B#439]     at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[B#439]     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[B#439]     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[B#439]     at java.awt.EventDispatchThread.run(Unknown Source)
[B#439] Caused by: net.technicpack.launchercore.exception.RestfulAPIException: Error accessing URL [http://www.technicpack.net/api/modpack/the-diamond-dimensions]
[B#439]     at net.technicpack.launchercore.restful.RestObject.getRestObject(RestObject.java:109)
[B#439]     at org.spoutcraft.launcher.skin.options.ImportOptions$2.doInBackground(ImportOptions.java:285)
[B#439]     at org.spoutcraft.launcher.skin.options.ImportOptions$2.doInBackground(ImportOptions.java:281)
[B#439]     at javax.swing.SwingWorker$1.call(Unknown Source)
[B#439]     at java.util.concurrent.FutureTask.run(Unknown Source)
[B#439]     at javax.swing.SwingWorker.run(Unknown Source)
[B#439]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[B#439]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[B#439]     at java.lang.Thread.run(Unknown Source)
[B#439] Caused by: java.net.BindException: Cannot assign requested address: connect
[B#439]     at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
[B#439]     at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
[B#439]     at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
[B#439]     at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
[B#439]     at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
[B#439]     at java.net.PlainSocketImpl.connect(Unknown Source)
[B#439]     at java.net.SocksSocketImpl.connect(Unknown Source)
[B#439]     at java.net.Socket.connect(Unknown Source)
[B#439]     at sun.net.NetworkClient.doConnect(Unknown Source)
[B#439]     at sun.net.www.http.HttpClient.openServer(Unknown Source)
[B#439]     at sun.net.www.http.HttpClient.openServer(Unknown Source)
[B#439]     at sun.net.www.http.HttpClient.<init>(Unknown Source)
[B#439]     at sun.net.www.http.HttpClient.New(Unknown Source)
[B#439]     at sun.net.www.http.HttpClient.New(Unknown Source)
[B#439]     at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
[B#439]     at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
[B#439]     at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
[B#439]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#439]     at net.technicpack.launchercore.restful.RestObject.getRestObject(RestObject.java:89)
[B#439]     ... 8 more

I'm not sure if it helps, but that's what it says when I try to add a new pack.

**Comment by Radio910** [comment]
Same exact thing for me! We must get an answer!!!

**Comment by ToasterShark** [comment]
I read earlier post, and it said to check your programs and uninstall "relevant knowledge" if you have it.

**Comment by Radio910** [comment]
What do you mean?

**Comment by ToasterShark** [comment]
This link https://github.com/TechnicPack/TechnicLauncher/issues/540

That should tell you what I mean

**Comment by ToasterShark** [comment]
I don't know why but suddenly it worked. :+1:

**Comment by HomelessTR** [comment]
pls help i can't connect pls

**Comment by ToasterShark** [comment]
Connect to what?
